blueprint:
  name: Heating Floor Control by Temperature
  description: Automatically control heating floors based on temperature thresholds.
  domain: automation
  input:
    temperature_sensor:
      name: Temperature Sensors
      description: List of temperature sensors for each room.
      selector:
        entity:
          domain: sensor
    heating_switch:
      name: Heating Switches
      description: List of switches controlling the heating floors for each room.
      selector:
        entity:
          domain: switch
    max_temperature:
      name: Maximum Temperature
      description: Temperature above which heating will turn off.
      default: 23
      selector:
        number:
          min: 15
          max: 30
          unit_of_measurement: °C
          mode: slider
    min_temperature:
      name: Minimum Temperature
      description: Temperature below which heating will turn on.
      default: 21
      selector:
        number:
          min: 15
          max: 30
          unit_of_measurement: °C
          mode: slider
trigger:
  - platform: state
    entity_id: !input temperature_sensor
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            above: !input max_temperature
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heating_switch
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            below: !input min_temperature
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heating_switch
mode: parallel
